### PR TITLE
Feature/sendgrid

### PR DESCRIPTION
**Pull request by benhowes**
Hi cpwood,

I've taken the liberty of adding support for sending receipts to Receipt Bank using the sendgrid mail API. I've done this for a few reasons:
1. Reliable API with paid options - I don't mean to cause offense, but not sure I want to host a version of your API or rely on yours always being available!
2. Ability to CC your own address in for backup.

I've also bumped the version to `0.1.0`, hopefully this is okay?

The README has been updated to include instructions on sendgrid setup and development steps which I worked out from the gulpfile :)

### CODE REVIEW

**Comment by benhowes** [comment]
I've had word from reciept bank this morning that there is an API and I have documentation for it. It uses a similar multipart/form structure to the sendgrid integration, however it needs an OAuth login first. I'll have a look at this one evening this week and update the pull request. Neither emailing service will be required in this case, so suggest that only API integration is left in?

**Comment by cpwood** [comment]
Thanks for all the hard work @benhowes over the weekend! Just been catching up on all the stuff you've submitted.

That does definitely sound like the best way forward and thanks for offering to look at it. I've got *very* limited time available at the moment so you taking all this work on is very much appreciated!

**Comment by benhowes** [comment]
Hi @cpwood - I've just reviewed the Receipt bank API docs, they only provide a means to upload an image at the moment, which of course would mean rendering the contents in a background page and getting a screenshot of that (if you can do that?). I feel that for now it might be best to stick with sending the email attachments because at least they accept PDF's in this form! I will raise this with them, but not expecting a lot from it.

So happy to discuss, but I'm feeling that using a free sendgrid account is a better route to keeping control of company data and doesn't rely on having your server doing all the forwarding! I appreciate the server code is open source too, but really didn't fancy having another service to keep running on my server.

At the moment, I've made it so that you can choose which sending service to use, so it shouldn't break anything for you or anyone else.

Thanks for the module, it's certainly a massive improvement for me, especially for adding invoices from amazon!

**Comment by benhowes** [comment]
I did get a reply from receipt bank in the end - apparently you can submit anything through the api (through an attribute called image). So the extension would simply need to be able to fetch an oauth key and then it would be able to directly upload without email. Seems like a solid way forward.

**Comment by cpwood** [comment]
Fantastic - thanks for the update, @benhowes !

**Comment by benhowes** [comment]
@cpwood was looking at this more, I think there are going to be some issues with a chrome only service and the oauth flow which will need to have the a secret key in the packaged app - this would be a fairly big security concern for people logging in I think.

Overall, I think that the sendgrid option is the best for now, so I suggest that it probably is worth merging this in, then possibly just using that rather than the service you're currently running?

I've been using my fork daily since three weeks ago when I opened this PR and it's all been running smoothly.

I'll leave it to you from here. Cheers!

**Comment by cpwood** [comment]
Thanks Ben!

Quick question for you: have you had any performance problems with any
sites that happen to use Bootstrap for CSS? The extension tries to "inline"
any relevant CSS classes so there's no dependency on externally hosted CSS
files, but I've seen it completely crap-out with Bootstrap sites..

**Comment by benhowes** [comment]
I've not seen this, however I mainly use for email forwarding from gmail.

I would suggest that taking screenshots may actually be easier and produce smaller files - I did this exact thing in the past for making mockups of adding a widget to peoples websites. The imgur extension demonstrates really good ways of getting the screenshots (some CSS mods needed for sticky headers on long pages).

Cheers.

**Pull request closed without merging**
